name: CI

on: [push, pull_request]

env:
 DATABASE_URL: 'https://example.com'
 NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: 'key'
 CLERK_SECRET_KEY: 'key'

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout
     uses: actions/checkout@v2
     
   - name: Install deps
     run: npm ci
     
   - name: lint
     run: npm run lint
