name: CI

on: [push, pull_request]

env:
  DATABASE_URL: 'https://example.com'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout
       uses: actions/checkout@v2
      -name: install dependencies
        run: npm ci
      -name: typecheck
        run: npm run typecheck
      -name: lint
        run: npm run lint